overrides:
  html-minifier-terser: npm:html-minifier-next
  vite: ^7.3.2
  lightningcss: ^1.32.0

onlyBuiltDependencies:
  - esbuild
  - sharp

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600
